# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest
stages:
    - build
    - testing
    - cleanup

before_script:
  - git config --global user.name "chandan"
  - git config --global user.email "cjha@cavium.com"
   
after_script:
  - echo "After script section"
   
build_n5drv:
  stage: build
  tags:
    - n5_drv
  script:
    - /home/git_build/nitrox_build_test.sh
   
drvload_tests:
  stage: testing
  tags:
    - n5_drv
  script: 
    - /home/git_build/nitrox_drv_loadtest.sh 

sample_tests:
  stage: testing
  tags:
    - n5_drv
  script: 
    - /home/git_build/nitrox_drv_sample_test.sh
   
cleanup:
  stage: cleanup
  tags: 
    - n5_drv
  script:
    - /home/git_build/nitrox_cleanup.sh 
